### ISSUE TITLE
Imagens

### ISSUE THREAD

**Issue by gabrielrcouto** [MemedDev/sinapse#1]

**Comment by gabrielrcouto** [comment]
![exemplo memed autocomple input sintese](https://cloud.githubusercontent.com/assets/2197005/22080162/b344340e-dda5-11e6-841b-13486c61548c.gif)

**Comment by marcelribeiroo** [comment]
![sinapse-banner](https://cloud.githubusercontent.com/assets/21063429/22125185/dc816196-de79-11e6-96e1-b29105833d5b.png)

**Comment by marcelribeiroo** [comment]
![sinapse_setup](https://cloud.githubusercontent.com/assets/21063429/22165942/94636a5e-df45-11e6-8f52-21cd7d242275.gif)

**Comment by gabrielrcouto** [comment]
![brando_new 2x](https://cloud.githubusercontent.com/assets/2197005/23463496/7c1e6e90-fe70-11e6-84d8-5a815c6b7890.png)

**Comment by gabrielrcouto** [comment]
![captura de tela 2017-03-02 as 16 27 53](https://cloud.githubusercontent.com/assets/2197005/23523343/4624fdd6-ff65-11e6-89ca-fcbc6e707573.png)

**Comment by gabrielrcouto** [comment]
![captura de tela 2017-03-02 as 16 31 11](https://cloud.githubusercontent.com/assets/2197005/23523445/b35bd000-ff65-11e6-8c6d-5c0c5264c8e3.png)

**Comment by gabrielrcouto** [comment]
![screen shot 2018-04-06 at 17 48 38-fullpage](https://user-images.githubusercontent.com/2197005/38443811-53d52ab6-39c3-11e8-9f7a-a1fb8e6aeafd.png)

**Comment by gabrielrcouto** [comment]
![captura de tela 2018-07-18 as 15 42 31](https://user-images.githubusercontent.com/2197005/42901189-472bf1c6-8aa1-11e8-86fd-9744bffd0c41.png)

**Comment by gabrielrcouto** [comment]
![thumb crop prescricao](https://user-images.githubusercontent.com/2197005/42904636-ff2217ba-8aab-11e8-9d96-13b5efc5b71d.png)

**Comment by gabrielrcouto** [comment]
![ver exemplo](https://user-images.githubusercontent.com/2197005/42910640-afbd2fb2-8abe-11e8-9d63-01df904b5271.png)
