### ISSUE TITLE
Adicionar opção para desativar a funcionalidade de Protocolos

### ISSUE THREAD

**Issue by diegourban** [MemedDev/sinapse#17]
Gostaria que fosse possível desativar a funcionalidade de Protocolos para que ela não fosse renderizada tanto na barra superior durante a criação/edição de uma prescrição como a opção de "Salvar como Protocolo" na tela de Impressão.

Obrigado.

**Comment by cjsjtec** [comment]
Boa tarde @diegourban.
Para qual o nome da empresa que está solicitando?
