### ISSUE TITLE
Adicionar parâmetro indicando se é receita especial no callback medicamentoAdicionado

### ISSUE THREAD

**Issue by MaiaVinicius** [MemedDev/sinapse#2]
Preciso do indicador se é receita especial ou não no evento callback medicamentoAdicionado, pois no nosso software, se for especial, ao imprimir a receita, ela deve ser gerada completamente diferente.
Obrigado.

**Comment by williamespindola** [comment]
@MaiaVinicius foi adicionado `  //    "controle_especial":false,` no commit [5e4364b](https://github.com/MemedDev/sinapse/commit/6060f7e5a0b8be3ae33f9c94273c3378cfad7319) atende?

**Comment by williamespindola** [comment]
@MaiaVinicius vou fechar a issue por falta de interatividade, se tiver mais alguma dúvida fique a vontade para nos contatar.
