### ISSUE TITLE
Problema com CORS em requisições preflight

### ISSUE THREAD

**Issue by PedroVinicius** [MemedDev/sinapse#21]
Prezados, estou neste momento integrando a SPA de um cliente à API do memed, e durante o desenvolvimento estou utilizando a sandbox para meus testes. No entanto, estamos tendo problemas com chamadas à API a partir do `HttpClient` do Angular 7. O que acontece, é que pelo fato de ser necessário o envio do header `Content-Type`, o browser está enviando requisições preflight ao endpoint destinado ao cadastramento de usuários. Aparentemente o referido endpoint não suporta o verbo `Options`, o que causa erro de CORS. O que pode ser feito neste caso? Existe alguma forma de contornar o problema? Infelizmente a integração a partir do backend não é uma opção.

A título de informação, segue um print contendo o erro que estou recebendo como resposta:

![image](https://user-images.githubusercontent.com/3680489/88460618-5e8d7800-ce95-11ea-95f5-549d585d2f19.png)

**Comment by cjsjtec** [comment]
@PedroVinicius entre em contato com nosso time de atendimento.

 https://ajuda.memed.com.br
